<script setup>
import {ref,computed,onMounted} from 'vue';import {Bookmark,Share2,Clock,ChevronRight,Play,WifiOff,Download,CheckCircle2} from 'lucide-vue-next';
const cats=['તમારા માટે','રાજકોટ','ગુજરાત','દેશ','વિશ્વ','બિઝનેસ','સ્પોર્ટ્સ','ટેક'];
const active=ref('તમારા માટે'),saved=ref(JSON.parse(localStorage.getItem('savedNews')||'[]'));
const stories=[
{id:1,cat:'રાજકોટ',title:'શહેરમાં નવા વિકાસ પ્રોજેક્ટને મંજૂરી, રસ્તા અને જાહેર પરિવહન પર ખાસ ધ્યાન',summary:'નાગરિક સુવિધાઓમાં સુધારો લાવવા માટે તબક્કાવાર કામગીરી શરૂ થશે.',time:'12 મિનિટ પહેલાં',img:'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=900&q=75'},
{id:2,cat:'ગુજરાત',title:'ગુજરાતના અનેક વિસ્તારોમાં વરસાદી માહોલ, ખેડૂતો માટે નવી માર્ગદર્શિકા જાહેર',summary:'હવામાનમાં બદલાવને ધ્યાનમાં રાખી ખેતી માટે જરૂરી સૂચનાઓ આપવામાં આવી.',time:'28 મિનિટ પહેલાં',img:'https://images.unsplash.com/photo-1519692933481-e162a57d6721?auto=format&fit=crop&w=900&q=75'},
{id:3,cat:'બિઝનેસ',title:'ડિજિટલ પેમેન્ટ અને નાના વ્યવસાયોમાં નવી ટેકનોલોજીનો ઉપયોગ ઝડપથી વધ્યો',summary:'સ્થાનિક વેપારીઓ હવે બિલિંગથી લઈને ગ્રાહક સેવા સુધી ડિજિટલ સાધનો અપનાવી રહ્યા છે.',time:'45 મિનિટ પહેલાં',img:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=75'},
{id:4,cat:'સ્પોર્ટ્સ',title:'આગામી શ્રેણી માટે ટીમની જાહેરાત, યુવા ખેલાડીઓને મળી મહત્વની તક',summary:'પસંદગી સમિતિએ અનુભવ અને નવા પ્રતિભાશાળી ખેલાડીઓનું સંતુલન રાખ્યું.',time:'1 કલાક પહેલાં',img:'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=900&q=75'}];
const filtered=computed(()=>active.value==='તમારા માટે'?stories:stories.filter(s=>s.cat===active.value));
function save(id){saved.value=saved.value.includes(id)?saved.value.filter(x=>x!==id):[...saved.value,id];localStorage.setItem('savedNews',JSON.stringify(saved.value))}
onMounted(()=>localStorage.setItem('offlineStories',JSON.stringify(stories)));
</script>
<template><div class="news-app"><div class="breaking-card"><span>બ્રેકિંગ</span><b>આજના મહત્વના સમાચાર અને તમારા શહેરની લાઇવ અપડેટ્સ</b><ChevronRight/></div><div class="category-scroll"><button v-for="c in cats" :class="{active:active===c}" @click="active=c">{{c}}</button></div><section class="lead-story"><img src="https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=78"><div class="lead-overlay"><span>ગુજરાત વિશેષ</span><h1>ગુજરાતમાં વિકાસ, ટેકનોલોજી અને સ્થાનિક સમાચારની આજની સંપૂર્ણ તસવીર</h1><p><Clock/> 8 મિનિટ પહેલાં · 5 મિનિટ વાંચન</p></div></section><div class="quick-grid"><router-link to="/shorts"><span class="quick-icon red"><Play/></span><b>60 સેકન્ડ<br>ન્યૂઝ</b></router-link><a><span class="quick-icon blue"><NewspaperIcon/></span><b>આજનું<br>ઈ-પેપર</b></a><router-link to="/polls"><span class="quick-icon amber">%</span><b>આજનો<br>પોલ</b></router-link><a><span class="quick-icon green"><Download/></span><b>ઓફલાઇન<br>ડાઉનલોડ</b></a></div><div class="section-head"><h2>તમારા માટે</h2><span>અપડેટેડ હમણાં</span></div><article v-for="s in filtered" :key="s.id" class="feed-card"><div class="feed-copy"><span class="story-cat">{{s.cat}}</span><h3>{{s.title}}</h3><p>{{s.summary}}</p><small>{{s.time}}</small><div class="feed-actions"><button @click="save(s.id)" :class="{saved:saved.includes(s.id)}"><Bookmark/> {{saved.includes(s.id)?'સેવ થયું':'સેવ'}}</button><button><Share2/> શેર</button></div></div><img :src="s.img"></article><section class="offline-card"><WifiOff/><div><b>ઓફલાઇન વાંચન તૈયાર</b><p>તમે વાંચેલા અને સેવ કરેલા સમાચાર ઉપકરણમાં રહે છે. ઇન્ટરનેટ પાછું આવે ત્યારે માત્ર બદલાયેલા સમાચાર સિંક થશે.</p></div><CheckCircle2/></section><section class="short-strip"><div class="section-head"><h2>ન્યૂઝ શોર્ટ્સ</h2><router-link to="/shorts">બધા જુઓ</router-link></div><div class="short-row"><router-link v-for="(s,i) in stories.slice(0,3)" to="/shorts" :key="s.id"><img :src="s.img"><span><Play/> 60 sec</span><b>{{s.title}}</b></router-link></div></section></div></template>
<script>const NewspaperIcon={template:'<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 4h16v16H4z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg>'};export default{components:{NewspaperIcon}}</script>