<script setup>
import {ref,onMounted,onBeforeUnmount} from 'vue';import {Heart,MessageCircle,Share2,Bookmark,Volume2,VolumeX,Play,Pause,Sparkles,ChevronDown} from 'lucide-vue-next';
const liked=ref(new Set(JSON.parse(localStorage.getItem('likedShorts')||'[]'))),saved=ref(new Set(JSON.parse(localStorage.getItem('savedShorts')||'[]'))),muted=ref(true),auto=ref(true),active=ref(0),root=ref(null),timer=ref(null);
const shorts=[
{id:1,cat:'ટેકનોલોજી',title:'AI ટૂલ્સથી નાના વ્યવસાયનું કામ કેવી રીતે બદલાઈ રહ્યું છે?',text:'ગ્રાહક સેવા, ડિઝાઇન અને રોજિંદા કામગીરીમાં નવી ટેકનોલોજી ઝડપથી ઉપયોગી બની રહી છે.',img:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=82',likes:'12.4K'},
{id:2,cat:'ગુજરાત',title:'શહેરના નવા પરિવહન રૂટથી મુસાફરી વધુ સરળ બનશે',text:'નવા રૂટ અને ડિજિટલ માહિતી વ્યવસ્થા દ્વારા મુસાફરોને ઝડપી જોડાણ આપવાનો પ્રયાસ.',img:'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=900&q=82',likes:'8.7K'},
{id:3,cat:'બિઝનેસ',title:'મોબાઇલ પેમેન્ટ નાના વેપારીઓ માટે કેમ મહત્વનું બની રહ્યું છે?',text:'ઝડપી ચુકવણીથી લઈને ડિજિટલ હિસાબ સુધીની સેવાઓ સ્થાનિક બજારમાં બદલાવ લાવી રહી છે.',img:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=82',likes:'9.1K'},
{id:4,cat:'સ્પોર્ટ્સ',title:'યુવા ખેલાડીઓ માટે મોટી તક: 60 સેકન્ડમાં જાણો મુખ્ય વાત',text:'આગામી સ્પર્ધા પહેલાં ટીમ તૈયારી અને પસંદગી વિશેની ઝડપી માહિતી.',img:'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=900&q=82',likes:'15K'}];
function persist(){localStorage.setItem('likedShorts',JSON.stringify([...liked.value]));localStorage.setItem('savedShorts',JSON.stringify([...saved.value]))}
function toggle(set,id){set.value.has(id)?set.value.delete(id):set.value.add(id);set.value=new Set(set.value);persist()}
function share(s){if(navigator.share)navigator.share({title:s.title,text:s.text,url:location.href});else navigator.clipboard?.writeText(location.href)}
function schedule(){clearTimeout(timer.value);if(auto.value)timer.value=setTimeout(()=>{const el=root.value?.children[active.value+1];if(el)el.scrollIntoView({behavior:'smooth'})},8000)}
onMounted(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.7){active.value=Number(e.target.dataset.i);schedule()}}),{root:root.value,threshold:[.7]});[...root.value.children].forEach(e=>obs.observe(e));root.value._obs=obs;schedule()});
onBeforeUnmount(()=>{clearTimeout(timer.value);root.value?._obs?.disconnect()});
</script>
<template><div class="reels-wrap"><div class="reels-toolbar"><b><Sparkles/> PULSE SHORTS</b><button @click="auto=!auto">{{auto?'Auto ON':'Auto OFF'}} <Pause v-if="auto"/><Play v-else/></button></div><div ref="root" class="reels-feed"><article v-for="(s,i) in shorts" :key="s.id" :data-i="i" class="reel-full" :style="{backgroundImage:`linear-gradient(0deg,rgba(7,7,8,.96) 0%,rgba(7,7,8,.35) 48%,rgba(0,0,0,.08) 100%),url(${s.img})`}"><div class="reel-progress"><i :class="{running:i===active&&auto}"></i></div><button class="mute" @click="muted=!muted"><VolumeX v-if="muted"/><Volume2 v-else/></button><div class="reel-copy"><span>{{s.cat}}</span><h1>{{s.title}}</h1><p>{{s.text}}</p><small>60 સેકન્ડમાં સમાચાર</small></div><aside><button @click="toggle(liked,s.id)" :class="{hot:liked.has(s.id)}"><span><Heart :fill="liked.has(s.id)?'currentColor':'none'"/></span><b>{{liked.has(s.id)?'Liked':s.likes}}</b></button><button><span><MessageCircle/></span><b>ચર્ચા</b></button><button @click="toggle(saved,s.id)" :class="{gold:saved.has(s.id)}"><span><Bookmark :fill="saved.has(s.id)?'currentColor':'none'"/></span><b>સેવ</b></button><button @click="share(s)"><span><Share2/></span><b>શેર</b></button></aside><div v-if="i===0" class="swipe-hint"><ChevronDown/> ઉપર સ્વાઇપ કરો</div></article></div></div></template>